### ISSUE TITLE
我想问下，在苹果端，返回上一页，某些界面，我不想拥有侧滑返回的功能，怎么实现。

### ISSUE THREAD

**Issue by tianyuming0329** [theyakka/fluro#107]

**Comment by lukef** [comment]
This is a question better asked on StackOverflow and not here. It is likely to get better responses on StackOverflow.

A quick search found this: https://stackoverflow.com/questions/49161644/flutter-disable-swipe-to-navigate-back-in-ios.

Hope it's helpful.
