### ISSUE TITLE
Cupertinal,Are you kidding me?

### ISSUE THREAD

**Issue by kukugtu** [theyakka/fluro#110]
<img width="530" alt="图片" src="https://user-images.githubusercontent.com/20319391/60712179-006bbb00-9f49-11e9-8693-0a358736e4ae.png">

**Comment by Yuzopro** [comment]
![image](https://user-images.githubusercontent.com/47881647/61424647-cd60f880-a946-11e9-9875-465437850ba2.png)
There's a question here！！！

**Comment by lukef** [comment]
Fixed in 1.5.1
