### ISSUE TITLE
What's the difference between fluro's TransitionType's cupertino, cupertino FullScreenDialog? 

### ISSUE THREAD

**Issue by Alexwsc** [theyakka/fluro#111]
What's the difference between fluro's TransitionType's cupertino, cupertino FullScreenDialog? Doesn't it feel any different? The effect is the same. And there is a lot of problems with this aspect, is there a problem with the source code itself?

**Comment by lukef** [comment]
Please see the flutter docs for the differences:

```
  /// In Material and Cupertino, being fullscreen has the effects of making
  /// the app bars have a close button instead of a back button. On
  /// iOS, dialogs transitions animate differently and are also not closeable
  /// with the back swipe gesture.
```
