### ISSUE TITLE
build method was executed twice

### ISSUE THREAD

**Issue by LZQL** [theyakka/fluro#116]
my page is a StatefulWidget, my build method is 
```
  Widget build(BuildContext context) {
    print("build");
    return Scaffold(
      appBar: AppBar(title: Text('test'),)
      body: Container(
        height: 222,
        color: Colors.red,
      ),
    );
```
when i use Application.router.navigateTo(context, Routes.xxx);  to  open the page.
the build method was executed twice.

but , i use 
Navigator.push(
        context, new CupertinoPageRoute<void>(builder: (ctx) => page));
it  is ok,only executed one.

why？ i only need one，because if executed twice my Network request will executed twice.
because  BlocBuilder will  executed twice

**Comment by LZQL** [comment]
Just to clarify， when i use in ios,it  is OK,all is  executed one. 
But in Android,  Application.router.navigateTo()   is   executed twice ,  Navigator.push() is  executed one

**Comment by LZQL** [comment]
Very strange， when my build method Scaffold no appbar , in android and ios, it is all executed one.

Widget build(BuildContext context) {
     print("build");
     return Scaffold(
                    body: Container(
                                  height: 222,
                                 color: Colors.red,
                    ),
       );

**Comment by sm9i** [comment]
'initState' Executed twice??I also met, debug is normal, but release will execute twice

**Comment by LZQL** [comment]
> 'initState' Executed twice??I also met, debug is normal, but release will execute twice

I haven't test release,  now i only find 'build(BuildContext context)’ Executed twice in android.

**Comment by lukef** [comment]
See: https://github.com/flutter/flutter/issues/14124.

As Ian says, the build method should be idempotent and cannot be guaranteed to be called just once per operation.

**Comment by lukef** [comment]
If you think it is a bug, I suggest logging the issue on the Flutter github repo.
