### ISSUE TITLE
Excuse me,Parameter truncated.

### ISSUE THREAD

**Issue by pheromone** [theyakka/fluro#117]
打扰一下,参数被截取.
Excuse me,Parameter truncated.
![image](https://user-images.githubusercontent.com/14305431/62845287-5fb3ac80-bcf9-11e9-8269-b7c8da8c7fad.png)
![image](https://user-images.githubusercontent.com/14305431/62845294-71954f80-bcf9-11e9-9890-4983b19d3ee9.png)
+ 被删了?
+ are deleted?

**Comment by lukef** [comment]
You probably need to encode the value first. There are many examples of the same question in the issues.
