### ISSUE TITLE
Could you add optional Handler when before navigateTo ？

### ISSUE THREAD

**Issue by bestK** [theyakka/fluro#122]
**Is your feature request related to a problem? Please describe.**
> I need before navigateTo do something ,E.g check user has login

**Describe the solution you'd like**
> An optional function argument

**Describe alternatives you've considered**
> Change your source code

**Additional context**
> ![image](https://user-images.githubusercontent.com/14979305/64247329-33c6c800-cf41-11e9-893e-716890ce3d20.png)

**Comment by quetool** [comment]
How did you achieve this in `route.define`?

**Comment by freshgeek** [comment]
show you code please

**Comment by bestK** [comment]
time so long ,i forget, sorry @freshgeek

**Comment by freshgeek** [comment]
It's okay, I roughly understand now
Maybe like this ：

```
router.define(setting, handler: Handler(
        handlerFunc: (BuildContext? context, Map<String, List<String>> params) {
      return checkLogin(context, const AppSetterPage());
    }));


  static Widget checkLogin(context, Widget widget) {
    return ScopedModelHelper.getModel<AuthModel>(context).isLogin
        ? widget
        : LoginPage();
  }
```

NO filter is bad
