### ISSUE TITLE
How to pass data which contain `/` ?

### ISSUE THREAD

**Issue by tronghuy5555** [theyakka/fluro#129]
Is there any ways to pass data contain `/`?. If i pass data contain `/`, it would show exception related "not define RouteSetting".

**Comment by timrijckaert** [comment]
In our app we base64SafeEncode the string.  
You can use this helper class.  

```dart
import 'dart:convert';

class UrlSafeBase64Helper {
  static final _base64SafeEncoder = const Base64Codec.urlSafe();

  String encodeStringToBase64UrlSafeString(final String url) => _base64SafeEncoder.encode(utf8.encode(url));

  String decodeFromBase64UrlSafeEncodedString(String str) => utf8.decode(_base64SafeEncoder.decode(str));
}
```

**Comment by tronghuy5555** [comment]
I think encode data before sending to next page is a good solution. Thank you for your reply.
