### ISSUE TITLE
pop method in src/router.dart has wrong return type

### ISSUE THREAD

**Issue by epr3** [theyakka/fluro#144]
**Describe the bug**
As in the title, Navigator.pop returns void but the method is defined as returning bool.

**To Reproduce**
1. Try building and running the example app.
2. Observe the error.

**Expected behavior**
The app should build without errors.

**Screenshots**
<img width="1749" alt="Screenshot 2020-01-31 at 22 32 29" src="https://user-images.githubusercontent.com/17836403/73572770-499dd200-447a-11ea-9f96-ba4e12305962.png">

**Smartphone:**
 - Device: iPhone 11 simulator
 - OS: iOS 13
- Flutter version: v1.14.7-pre.67

**Comment by userhjp** [comment]
我也遇到这问题了，目前没找到解决办法，只能等fluto更新了吗？

**Comment by congthanhptnk** [comment]
I just got this error. For the time being, reverting back to Flutter version v1.12.13+hotfix.7 temporarily fixes the error

**Comment by lukef** [comment]
Closing in favour of #146. See comments there.
