### ISSUE TITLE
Flutter 1.15 introduces a breaking change

### ISSUE THREAD

**Issue by piratejason** [theyakka/fluro#146]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by piratejason** [comment]
version 1.5.1

**Comment by piratejason** [comment]
it's bug 
fluro-1.5.1/lib/src/router.dart:41:47: Error: This expression has type 'void' and can't be used.
  bool pop(BuildContext context) => Navigator.pop(context);

**Comment by e-lobo** [comment]
@piratejason  if you use flutters stable branch it will work.. seems like this happens with flutters master branch. anybody find any fixes?

**Comment by lukef** [comment]
It's not a bug. Flutter's policy is to push breaking changes at any time. As a result, we only support stable branches either way. I'll take a look at why it's breaking and possibly push an unstable version of Fluro. It's not possible from a practical standpoint to support both the unstable and stable versions of Flutter at the same time.

**Comment by evansherry** [comment]
@lukef This caused us a lot of problems after upgrading to 1.15.
 Can you support a branch?

**Comment by william-xue** [comment]
when upgraded to 1.14+, fluro cannot work well

**Comment by Moosphan** [comment]
After upgraded my flutter master branch version, i faced the same problem. When can this problem be fixed?

**Comment by geekz-reno** [comment]
yes, same here, master, dev branch

**Comment by lukef** [comment]
1.6 should resolve this
