### ISSUE TITLE
handlerFunc repeated called when TextField focus or lost focus, keyboard shows or hides.

### ISSUE THREAD

**Issue by longdw** [theyakka/fluro#152]
Flutter: v1.9.1-pre.58
Fluro: v1.5.2
Problem：handlerFunc repeated called when TextField focus or lost focus, keyboard shows or hides.
DEMO：[test_fluro_rebuild_bug](https://github.com/longdw/test_fluro_rebuild_bug.git)

**Comment by longdw** [comment]
I get data with `widget.data` before, like this `Bean get data => widget.data.`
but solved the problem temporarily when I pass the data from Page(data) to State(data) and init the data in State Construction method.

**Comment by brianschardt** [comment]
@longdw i am running into the same issue. not sure i understand your solution
