### ISSUE TITLE
Navigator.pop(context); has no return value because it is void.

### ISSUE THREAD

**Issue by ilshookim** [theyakka/fluro#156]
Hi, I have a question about this:

I believe Navigator.pop(context) function has no return value because return type is void:
bool pop(BuildContext context) => Navigator.pop(context);

android studio build error:
../../../flutter/.pub-cache/hosted/pub.dartlang.org/fluro-1.4.0/lib/src/router.dart:38:47: Error: This expression has type 'void' and can't be used.
  bool pop(BuildContext context) => Navigator.pop(context);

I using to flutter mater channel and flutter doctor information:

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.16.2, on Mac OS X 10.15.4 19E266, locale ko-KR)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.43.2)
[✓] Connected device (4 available)

**Comment by devfelipereis** [comment]
I have the same using flutter master channel.

**Comment by devfelipereis** [comment]
It works with flutter 1.15.9.

**Comment by lukef** [comment]
Please read the README before posting...

`Version 1.6.0 (and higher) requires Flutter >= 1.12.0 and Dart >= 2.6.0. If you're running an older version of Flutter, use a version < 1.6.0.`
