### ISSUE TITLE
pub get failed (1; Because ones_mobile depends on fluro ^1.6.2 which doesn't match any versions, version solving failed.)

### ISSUE THREAD

**Issue by lyf571321556** [theyakka/fluro#157]
fluro: ^1.6.2

flutter pub get 

pub get failed (1; Because ones_mobile depends on fluro ^1.6.2 which doesn't match any versions, version solving failed.)

**Comment by lukef** [comment]
Not sure of your issue. 1.6.2 is on pub and 1.6.3 now also
