### ISSUE TITLE
Compatibility with Flutter 1.18

### ISSUE THREAD

**Issue by gcshri** [theyakka/fluro#162]
**Describe the bug**
Unable to install fluro with flutter 1.18.

**To Reproduce**
1. Add fluro to pubspec 
  fluro: "^1.6.2"
2. Run flutter pub get

**Expected behavior**
Fluro should install 

**Screenshots**
The current Flutter SDK version is 1.18.0.

Because <app_name> depends on fluro from git which requires Flutter SDK version >=1.12.0 <1.17.0, version solving failed.
pub get failed (1; Because <app_name> depends on fluro from git which requires Flutter SDK version >=1.12.0 <1.17.0, version solving failed.)
Process finished with exit code 1

**Additional context**
New project using flutter 1.18

**Comment by LJYq** [comment]
I also encountered the same issue.

**Comment by RymBenJmaa** [comment]
Same and if you try an older version you get the error: `Error: This expression has type 'void' and can't be used.
  bool pop(BuildContext context) => Navigator.pop(context);                                        `

**Comment by lukef** [comment]
1.6.3 is on pub now
