### ISSUE TITLE
Cannot find Route() after upgrading to version 1.22

### ISSUE THREAD

**Issue by seefs001** [theyakka/fluro#180]
**Describe the bug**
Cannot find Route() after upgrading to version 1.22

**To Reproduce**
1. upgraded to version 1.22
2. See error

**Desktop (please complete the following information):**
 - OS: Windows10 2004
 - Version: 1.6.0

Ref: 
https://medium.com/flutter/announcing-flutter-1-22-44f146009e5f
https://medium.com/flutter/learning-flutters-new-navigation-and-routing-system-7c9068155ade

**Comment by danialtheman** [comment]
@seefs001 Namespace clash. Try setting a prefix on the Fluro package when you import, and prefix the namespace name to the Route(), 

eg: 
`import 'package:fluro/fluro.dart' as FluroRouter;

class ...{
  FluroRouter.Route router = FluroRouter.Route();
`
