### ISSUE TITLE
Default TransitionType for route 

### ISSUE THREAD

**Issue by aloisdeniel** [theyakka/fluro#27]
Since the transition for a page is often the same, a default `TransitionType` could be given when defining routes.

```dart
_router.define(path,  handler: new Handler(handlerFunc: (c,p) => new Page()), transition: TransitionType.inFromLeft);
```

**Comment by lukef** [comment]
The default transition is `.native` for all routes if none is specified. Are you saying that for specific routes you want to always use the same transition?

**Comment by aloisdeniel** [comment]
When using `Navigator.of().pushNamed`, it does not currently use `.native`.

Yes, associating a transition to a route could be great.

**Comment by jonsamwell** [comment]
I just created a pull request for this.  Let me know your thoughts on it.  It would be good to add this functionality to this awesome library!

**Comment by lukef** [comment]
1.4.0 is published and should cover this. 2.0.0 (in development) will probably extend this (somewhat) but there are no plans for 2.0.0 to be backwards compatible.
