### ISSUE TITLE
Unable to pass url as a param using Fluro

### ISSUE THREAD

**Issue by viju85** [theyakka/fluro#44]
Hi,
I just started using Fluro and I noticed that I am unable to pass an URL as a param to my route object. Below is my route handler:
`var mediaViewerRouteHandler = new Handler(handlerFunc: (BuildContext context, Map<String, List<String>> params) {`
`    String mediaUrl = params["mediaUrl"].first;`
`   return new MediaViewerPage(mediaUrl: mediaUrl);`
`  });`
 ` router.define("/mediaviewer", handler: mediaViewerRouteHandler);`

This is my caller:
`var url = 'https://zdnet3.cbsistatic.com/hub/i/2012/11/26/278e55cc-1d11-11e4-8c7f-00505685119a/0d90f1dfd278e8f2e4ad4cf56f90455b/cloud-horizon.jpg';`
`String route = "/mediaviewer?mediaUrl={$url}";`
`router.navigateTo(context, route, transition: TransitionType.fadeIn);`

Below is my error:
No registered route was found to handle '/mediaviewer?mediaUrl=https://zdnet3.cbsistatic.com/hub/i/2012/11/26/278e55cc-1d11-11e4-8c7f-00505685119a/0d90f1dfd278e8f2e4ad4cf56f90455b/cloud-horizon.jpg'.
[VERBOSE-2:dart_error.cc(16)] Unhandled exception:
No registered route was found to handle '/mediaviewer?mediaUrl=https://zdnet3.cbsistatic.com/hub/i/2012/11/26/278e55cc-1d11-11e4-8c7f-00505685119a/0d90f1dfd278e8f2e4ad4cf56f90455b/cloud-horizon.jpg'.
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1114)

Please let me know how to pass a URL as a param.

**Comment by jbrw** [comment]
Encoding the URL that you wish to pass as a param before calling the router

`
        final encodedUrl = Uri.encodeComponent(imageUrl);
        router.navigateTo(context, 
                  "/images/view?imageUrl=$encodedUrl", 
                  transition: TransitionType.fadeIn); 
`

and then decoding the param in your handler:

`
var imageViewHandler = Handler(handlerFunc: (BuildContext context, Map<String, List<String>> params) {
  String encodedImageUrl = params["imageUrl"]?.first;
  final imageUrl = Uri.decodeQueryComponent(encodedImageUrl);

  return ImageViewScreen(imageUrl, minScale: 0.1, maxScale: 2.0);
});
`

seems to do the trick.

**Comment by jscottanderson** [comment]
@jbrw @lukef

I'm also experiencing the same issue, but my query parameters are unfortunately being configured by a third-party so I cannot encode them.

I have a route called /thanks with the following query parameters: ?firstName=John&lastName=Smith&url=https://google.com

I get the following error:

**The builder for route returned null
Route builders must never return null**

Is there anything I can do to fix this?
