### ISSUE TITLE
Reset Stack Navigation After push

### ISSUE THREAD

**Issue by pjcau** [theyakka/fluro#45]
Hi guys, 
thank you for this project that it's useful and very clear. So I need to reset the stack after loaded screen. If you think to iOS enviroment, reset a rootviewcontroller with the current VC.

**Comment by lukef** [comment]
I have added a `clearStack` argument to the navigate function. This should handle this use case. If you want to reset to root and clear the stack you can do `navigateTo(context, "/", clearStack: true)`.
