### ISSUE TITLE
Can not pass Vietnamese to the "path" parameter

### ISSUE THREAD

**Issue by nextfunc** [theyakka/fluro#47]
Everything works well with English.
When I switch to Vietnamese, the Home page show Vietnamese already. But when tapping on the button, I need to open next screen with Vietnamese. So I have to add Vietnamese to path as a parameter.
Unfortunately, I got error: 

> Another exception was thrown: Invalid argument(s): Illegal percent encoding in URI

Any suggestion? Thanks!

**Comment by facundomedica** [comment]
Encode the string with percent encoding or base64

**Comment by lukef** [comment]
Is this still an issue?
