### ISSUE TITLE
ios --release build TransitionType.native error

### ISSUE THREAD

**Issue by vagrantrobbie** [theyakka/fluro#51]
I am using Flutter SDK v0.4.4 and have just done a release build and am getting a fairly serious error when using the native transition type with iOS (Android is fine). 

the device screen goes black when the transition starts and an error is thrown
flutter: ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following NoSuchMethodError was thrown during paint():
flutter: Class '_CupertinoEdgeShadowPainter' has no instance method 'paint'.
flutter: Receiver: Instance of '_CupertinoEdgeShadowPainter'
flutter: Tried calling: paint(Instance of 'Canvas', Instance of 'Offset', Instance of 'ImageConfiguration')

If I set the-transition type to TransitionType.inFromRight, the navigation works fine.

Weirdly, this works fine in the debug mode.

iPhone 5s, iOS 11(.3.1)

**Comment by lukef** [comment]
Are you able to validate this against the latest version of Flutter?
