### ISSUE TITLE
navigateTo' was called on null

### ISSUE THREAD

**Issue by hanxu317317** [theyakka/fluro#61]
i change my code from demo;

i get the error like this: "flutter: The method 'navigateTo' was called on null."
![image](https://user-images.githubusercontent.com/8518989/44853345-4d7f6080-ac98-11e8-8369-c121bbe2392f.png)

**Comment by ragasubekti** [comment]
Have you changed the route while the app is running? If yes then you need to hot refresh it afaik

**Comment by lukef** [comment]
Are you setting `Application.router` to anything?

**Comment by hanxu317317** [comment]
i don't not why~~~
this is my project address: [https://github.com/hanxu317317/flutter-test](https://github.com/hanxu317317/flutter-test)
`
can someone run it and click the **index**
![image](https://user-images.githubusercontent.com/8518989/45662907-6dd36a00-bb36-11e8-9650-c7372ab88599.png)
then u will get the error like this
![image](https://user-images.githubusercontent.com/8518989/45662931-8b083880-bb36-11e8-9048-9fc7633e2862.png)

**Comment by hanxu317317** [comment]
i fixed the problem , but i didn't learn why
i createState by first ~ it's right but second it will go wrong.

first:
```
  _DemoState createState() => new _DemoState();
```
second: 
```
State<StatefulWidget> createState() => new _DemoState();
```

```
class _DemoState  extends State<Demo> {
...
 new RaisedButton(
                child: new Text('index'),
                onPressed: () {
                  Application.router.navigateTo(context, "/index");
                },
              ),
...
```

**Comment by hanxu317317** [comment]
in [https://github.com/hanxu317317/flutter-test/blob/master/lib/view/demo/index.dart](https://github.com/hanxu317317/flutter-test/blob/master/lib/view/demo/index.dart) line 33.
