### ISSUE TITLE
navigateTo was called on null

### ISSUE THREAD

**Issue by emaddoma** [theyakka/fluro#66]
Example app works, but when identical app structure with different routes is run, I get this error.

[✓] Flutter (Channel beta, v0.8.2, on Mac OS X 10.13.6 17G65, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Community Edition (version 2018.2.4)
[✓] Connected devices (1 available)

`flutter: ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
flutter: The following NoSuchMethodError was thrown while handling a gesture:
flutter: The method 'navigateTo' was called on null.
flutter: Receiver: null
flutter: Tried calling: navigateTo(Instance of 'StatefulElement', "/demo")
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:48:5)
flutter: #1      LandingComponentState.build.<anonymous closure> (package:egc/components/landing/landing_component.dart:23:38)
flutter: #2      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:503:14)
flutter: #3      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:558:30)
flutter: #4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
flutter: #5      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
flutter: #6      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:175:7)
flutter: #7      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:315:9)
flutter: #8      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
flutter: #9      PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
flutter: #10     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:143:19)
flutter: #11     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
flutter: #12     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
flutter: #13     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
flutter: #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
flutter: #15     _invoke1 (dart:ui/hooks.dart:142:13)
flutter: #16     _dispatchPointerDataPacket (dart:ui/hooks.dart:99:5)`

**Comment by lukef** [comment]
It looks like your router instance is null. Please check the way you are referencing your router.

**Comment by quetool** [comment]
Hi, may be is too late, but I was having the same isuue, after a while, I did "flutter clean", the some errors came up. Fixing those error I was able to make it work

**Comment by facundomedica** [comment]
The cause for this in my project was that **the import path to application.dart was different in some files**.

For example, if in app_component.dart you use `import '../../config/application.dart';`, then use that notation in all your files. Sometimes autocompletion will offer `import 'package:yourprojectname/config/application.dart';` which will make this error come up. 

One simple way to check if this is your error it's to set breakpoints on every `navigateTo` and check for `Application` hashcode. You'll probably get at least 2 different numbers if something is wrong.
