### ISSUE TITLE
flutter packages get 

### ISSUE THREAD

**Issue by sabarinathancs** [theyakka/fluro#69]
pubspec.yaml
===>

name: helloword
description: A new Flutter project.

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  fluro:
    git:  git://github.com/theyakka/fluro.git
  flutter:
    sdk: flutter,

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

==========================================================================

flutter packages upgrade
Running "flutter packages upgrade" in helloword...               
Could not find a file named "pubspec.yaml" in git://github.com/theyakka/fluro.git a68b03e9cefa549d70885fe5390dee9d2c0ad30b.
 
pub upgrade failed (1)

**Comment by sabarinathancs** [comment]
Please help me to fix the routers in App

**Comment by sabarinathancs** [comment]
getting error too 

Running "flutter packages get" in helloword...                   
Because helloword depends on flutter any from sdk which doesn't exist (unknown SDK "flutter,"), version solving failed.
pub get failed (69) -- attempting retry 1 in 1 second...
Because helloword depends on flutter any from sdk which doesn't exist (unknown SDK "flutter,"), version solving failed.

**Comment by lukef** [comment]
Is there a reason you're using master vs the pub version? I just bumped the test package version (as it was old). Maybe give it another go?
