### ISSUE TITLE
The getter 'generator' was called on null

### ISSUE THREAD

**Issue by Kunoacc** [theyakka/fluro#70]
![image](https://user-images.githubusercontent.com/16244990/46905685-1040fc00-ceef-11e8-908f-42817fdc9f3c.png)
I get this error after integrating following the example.

**Comment by lukef** [comment]
Have you properly assigned the router instance to `Application.router`? You're calling `generator` on a null instance.

**Comment by MadeBugs** [comment]
demo是不是要更新一下，运行不起来
