### ISSUE TITLE
TransitionType.native should use CupertinePageRoute if on ios

### ISSUE THREAD

**Issue by shrugs** [theyakka/fluro#72]
Right now, the `TransitionType.native` configuration always uses a MaterialPageRoute. On iOS platforms, I'd expect the native transition to be dictated by a `CupertinoPageRoute`.

On [this line](https://github.com/theyakka/fluro/blob/master/lib/src/router.dart#L132), we could add a branch to check the runtime platform.

**Comment by lukef** [comment]
Fixed in `1.5.0`.
