### ISSUE TITLE
Not able to send param value as `+` in the .navigateTo path

### ISSUE THREAD

**Issue by Anuraag93** [theyakka/fluro#74]
I am trying to send phone number from one screen to another but the `+` in `+91 9123456789` is getting replaced by an empty space.

#### navigateTo
``` dart
var inputNumber = '+91 9123456789'; `
Application.router.navigateTo(context, '/phone_number?phonenum=$inputNumber');
```

#### Handling route 

```dart
 router.define("/phone_number", handler: _numHandler);
var _numHandler = Handler(
    handlerFunc: (BuildContext context, Map<String, List<String>> params) {
   String phoneNum = params["phonenum"]?.first;
  return RecieveNumberScreen(
      phoneNum: phoneNum,`
      );
});
```

#### Output:
 - `phoneNumber =  91 9123456789` 
- `+` is replaced with `<space>` on other end.

**Comment by lukef** [comment]
You should encode the value before sending and then decode it later
