### ISSUE TITLE
iOS not support swip back in 1.4.0

### ISSUE THREAD

**Issue by fengqiangboy** [theyakka/fluro#80]
iOS not support swip back in 1.4.0

it suport on 1.3.7 by default

**Comment by shamnex** [comment]
How do I use the Cupertino page route on android with fluro?

**Comment by AstrayV** [comment]
I found the same problem. So i have to use the fixed version fluro: 1.3.7, it doesnt support ^1.3.7.

**Comment by lukef** [comment]
Fixed in `1.5.0`.
